name: graph-xai-audit
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - captum=0.5.0
  - jupyter=1.0
  - matplotlib=3.4.3
  - mlflow
  - networkx=2.6.3
  - numba=0.55
  - numpy=1.21.2
  - pandas=1.3.3
  - scipy=1.7.1
  - scikit-learn=1.0
  - seaborn
  - tqdm=4.62.3
  - pyg>=2.0.4
  - pytest
  - pip
  - pip:
    - git+https://github.com/pyg-team/pytorch_geometric.git@df6110954405744639627f4ffb5dd27b4523239b
    - graphlime
